### ISSUE TITLE
Unable to configure firewalld

### ISSUE THREAD

**Issue by Hamuko** [scaleway/image-centos#13]
I'm unable to configure `firewalld` on a CentOS instance on a VC1S server. Every time I try to change the configuration, I get an `ERROR: INVALID_ZONE` message.

This is what I'm seeing in `/var/log/firewalld`.

```
2016-05-26 18:50:42 ERROR: ebtables not usable, disabling ethernet bridge firewall.
2016-05-26 18:50:43 ERROR: INVALID_ZONE
2016-05-26 18:58:15 ERROR: ebtables not usable, disabling ethernet bridge firewall.
2016-05-26 18:58:18 ERROR: INVALID_ZONE
2016-05-26 18:58:18 ERROR: INVALID_ZONE
2016-05-26 19:00:48 ERROR: ebtables not usable, disabling ethernet bridge firewall.
```

I already deleted one instance and recreated it because I thought I just buggered up something in the initial setup, but since this seems to be quite persistent, I'm guessing the particular instance wasn't the only thing that was wrong.

Trying to run `ebtables --list` also only logs errors.
```
[hamuko@hamuko ~]$ sudo ebtables --list
modprobe: FATAL: Module ebtables not found.
The kernel doesn't support the ebtables 'filter' table.
```

The following packages are installed on the instance:
* ebtables-2.0.10-13.el7.x86_64
* firewalld-0.3.9-14.el7.noarch
* iptables-1.4.21-16.el7.x86_64

**Comment by moul** [comment]
Hi @Hamuko, thank you for reporting,

I think we just need to add the ebtables kernel module on the kernel used by Centos, can you do:

1. from your current server, give me the result of the command `uname -a`
2. stop your server
3. from the console, [change your bootscript](https://www.scaleway.com/docs/bootscript-and-how-to-use-it/) to the one with *Docker* in the name (this alternate bootscript does have *ebtables*, I just expect it will allow you to boot with Centos)

As soon as we have this information, we can add the ebtables modules in your current bootscript

**Comment by Hamuko** [comment]
`Linux hamuko.moe 4.4.6-std-2 #1 SMP Mon Mar 21 13:41:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

firewalld seems to configure fine now if you run `yum install firewalld` as root. None of the previous errors pop up and I was able to add exceptions for ssh, http and https. However if you run it as non-root with `sudo yum install firewalld`, you get a bunch of errors when you try to start it up. Not really sure if this is a huge problem but I figured I should mention it just in case.

```
2016-05-27 07:22:46 ERROR: Exception DBusException: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.4" is not allowed to own the service "org.fedoraproject.FirewallD1" due to security policies in the configuration file
2016-05-27 07:22:51 ERROR: Exception DBusException: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.5" is not allowed to own the service "org.fedoraproject.FirewallD1" due to security policies in the configuration file
2016-05-27 07:23:32 ERROR: Exception DBusException: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.9" is not allowed to own the service "org.fedoraproject.FirewallD1" due to security policies in the configuration file
```

**Comment by ionutz22** [comment]
Hi,

I've managed to lock myself outside when I've tried to configure firewalld on a centos image (same kernel as above) using ansible. The worst part was I didn't set up a root password, so I wasn't able to connect over console :) (fist time using scaleway) ... but fixed in the end using rescue.

I've got the following errors when ansible tried to setup firewalld rules:

<snip>
TASK [firewalld : install firewalld] *******************************************
changed: [web01]
TASK [firewalld : ensure firewalld is running] *********************************
changed: [web01]
TASK [firewalld : add firewalld rules for services from vars] ******************
failed: [web01] (item={u'service': u'ssh'}) => {"failed": true, "item": {"service": "ssh"}, "module_stderr": "", "module_stdout": "/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_lqZz5B/ansible_module_firewalld.py\", line 605, in <module>\r\n    main()\r\n  File \"/tmp/ansible_lqZz5B/ansible_module_firewalld.py\", line 395, in main\r\n    is_enabled = get_service_enabled_permanent(zone, service)\r\n  File \"/tmp/ansible_lqZz5B/ansible_module_firewalld.py\", line 251, in get_service_enabled_permanent\r\n    fw_zone = fw.config().getZoneByName(zone)\r\n  File \"<string>\", line 2, in getZoneByName\r\n  File \"/usr/lib/python2.7/site-packages/slip/dbus/polkit.py\", line 103, in _enable_proxy\r\n    return func(*p, **k)\r\n  File \"<string>\", line 2, in getZoneByName\r\n  File \"/usr/lib/python2.7/site-packages/firewall/client.py\", line 52, in handle_exceptions\r\n    return func(*args, **kwargs)\r\n  File \"/usr/lib/python2.7/site-packages/firewall/client.py\", line 1505, in getZoneByName\r\n    path = dbus_to_python(self.fw_config.getZoneByName(name))\r\n  File \"/usr/lib64/python2.7/site-packages/dbus/proxies.py\", line 70, in __call__\r\n    return self._proxy_method(*args, **keywords)\r\n  File \"/usr/lib/python2.7/site-packages/slip/dbus/proxies.py\", line 50, in __call__\r\n    return dbus.proxies._ProxyMethod.__call__(self, *args, **kwargs)\r\n  File \"/usr/lib64/python2.7/site-packages/dbus/proxies.py\", line 145, in __call__\r\n    **keywords)\r\n  File \"/usr/lib64/python2.7/site-packages/dbus/connection.py\", line 651, in call_blocking\r\n    message, timeout)\r\ndbus.exceptions.DBusException: org.freedesktop.DBus.Python.dbus.exceptions.DBusException: INVALID_ZONE: public\r\n", "msg": "MODULE FAILURE", "parsed": false}
</snip>

PS: ON/OFF this kind of VPS is awful.

**Comment by biomap** [comment]
Is there a fix for this.  I tried to switch to the Docker bootscript and nada.  Tried Hamuko's "fix" but that doesn't work either.

**Comment by brmzkw** [comment]
Not sure it's related, but when running `firewalld --debug=10` I get the following error in `/var/log/firewalld`:

```
2016-06-24 09:27:24 DEBUG2: firewall.core.ipXtables.ip6tables: /sbin/ip6tables -w2 -t filter -I INPUT 1 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
2016-06-24 09:27:24 Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/firewall/server/decorators.py", line 40, in handle_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/firewall/server/firewalld.py", line 78, in start
    return self.fw.start()
  File "/usr/lib/python2.7/site-packages/firewall/core/fw.py", line 242, in start
    self._start()
  File "/usr/lib/python2.7/site-packages/firewall/core/fw.py", line 158, in _start
    self._apply_default_rules()
  File "/usr/lib/python2.7/site-packages/firewall/core/fw.py", line 516, in _apply_default_rules
    self.__apply_default_rules(ipv)
  File "/usr/lib/python2.7/site-packages/firewall/core/fw.py", line 505, in __apply_default_rules
    self.rule(ipv, _rule)
  File "/usr/lib/python2.7/site-packages/firewall/core/fw.py", line 575, in rule
    return self._ip6tables.set_rule(rule)
  File "/usr/lib/python2.7/site-packages/firewall/core/ipXtables.py", line 160, in set_rule
    return self.__run(rule)
  File "/usr/lib/python2.7/site-packages/firewall/core/ipXtables.py", line 156, in __run
    " ".join(_args), ret))
ValueError: '/sbin/ip6tables -w2 -t filter -I INPUT 1 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT' failed: ip6tables: Protocol wrong type for socket.
```

And indeed:

```
[root@test ~]# /sbin/ip6tables -w2 -t filter -I INPUT 1 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
ip6tables: Protocol wrong type for socket
```

**Comment by xcellardoor** [comment]
Having the same issue here. FirewallD is complaining about the lack of ebtables despite it being installed with yum already.

**Comment by QuentinPerez** [comment]
Hi @xcellardoor, can you use the latest docker bootscript and retry ?

**Comment by xcellardoor** [comment]
Already have I'm afraid, it didn't work for me.

If there's anything else you'd like me to try go ahead. I've swapped back to using Debian with UFW as a firewalled VPS solution for the time being.

I've read online that some components of FirewallD don't play well with OpenVZ? Is that the VM solution scaleway utilise?

**Comment by biomap** [comment]
When you switch over to the Docker bootscript you need to do a Hard Reboot from the console.  Then I had to:
`sudo yum reinstall firewalld`
  
to get mine working.  After a reload of firewalld or maybe a reboot (I cant remember)  firewalld should be using the tables.

They didn't provide much help but I hope this does.

**Comment by xcellardoor** [comment]
Oddly had to remove and then reinstall FirewallD twice... but it seems to be working now!

**Comment by biomap** [comment]
Cheers glad it worked!  You would think that since this is a core package for CentOS 7  they would have a guide at least (a fixed default bootscript would be nice too). But I will stop moaning  ;)

**Comment by Xlebomnekormi** [comment]
@biomap thanks man, you helped a lot!
scaleway's attitude towards centos is a bit weird))

**Comment by justinclift** [comment]
@Hamuko Is this still happening for you?

Asking because I've been setting up c1 instances with CentOS 7 today, and firewalld seems to be working without issue.  eg adding rules to the runtime and permanent config works, and they're correctly in place after rebooting

**Comment by ApertureSecurity** [comment]
I tried reinstalling but this didn't work..

I had to reboot the host and it started working.

**Comment by abdennour** [comment]
Unfortunately, it seems the issue with this new version `firewalld-0.4.4.4-14.el7.noarch.rpm`.

Anyway, rebooting the system fixes this issue. 🎉
Also make sure to stop iptables:  `systemctl status iptables` must return `Unit iptables.service could not be found`.

**Comment by mohammad7293** [comment]
@abdennour thanks very much
reboot worked for me

**Comment by zishang520** [comment]
```shell
sudo yum reinstall firewalld
sudo systemctl restart dbus
sudo systemctl restart firewalld
systemctl status -l firewalld
```
Active: active (running)

**Comment by justinclift** [comment]
@zishang520 Not sure if that will leave it running after boot.  You might also need to:

   systemctl enable firewalld

:smile:

**Comment by zishang520** [comment]
@justinclift thx
